services:
  remote_pc_humble:
    build: 
      context: ./
    image: ai_humble
    container_name: remote_pc_humble
    network_mode: host
    privileged: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PULSE_SERVER=unix:/tmp/pulse_socket
      - PULSE_COOKIE=/root/.config/pulse/cookie
      - ROS_DOMAIN_ID=30
      - TURTLEBOT3_MODEL=waffle_pi

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./my_code:/root/my_code
      - /run/user/${HOST_UID}/pulse/native:/tmp/pulse_socket
      - ${USER_HOME}/.config/pulse/cookie:/root/.config/pulse/cookie

    stdin_open: true
    tty: true
